services:
  redis:
    container_name: 'redis'
    image: 'redis:latest'
    ports:
      - 6379:6379
    networks:
      - app-redis-net
  shurl:
    container_name: 'shurl'
    image: 'malahor1610/shurl:latest'
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - app-redis-net
networks:
    app-redis-net:
      driver: bridge
