name: CI

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and publish image with Gradle to Docker Hub
        run: gradle bootBuildImage -Denv.DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} -Denv.DOCKER_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}